"""
Django settings for worldcup26 project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Dev-only fallback. With DEBUG=False (production) the guard below refuses to
# boot on it, so sessions/CSRF can never be signed with a public key.
_INSECURE_DEFAULT_SECRET_KEY = (
    "django-insecure-(lxwu=b&g_0p0otuuu2ri^153j#-k@54bvkm9^9zh5zl4@+p5s"
)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", _INSECURE_DEFAULT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# The Dockerfile bakes DEBUG=False into the production image; the True
# default only serves local development.
DEBUG = os.environ.get("DEBUG", "True") == "True"

if not DEBUG and SECRET_KEY == _INSECURE_DEFAULT_SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable must be set when DEBUG is False."
    )

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()
]
if not ALLOWED_HOSTS:
    # Convenience default for a fresh Railway deploy; an explicit
    # ALLOWED_HOSTS env var replaces it entirely.
    ALLOWED_HOSTS.append(".railway.app")
if DEBUG:
    ALLOWED_HOSTS += ["localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Set HTTPS_ONLY=True on Railway (TLS terminated at the proxy). Kept off in
# the local Docker simulation, which serves plain HTTP.
if os.environ.get("HTTPS_ONLY", "False") == "True":
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Conservative HSTS (1h, no subdomains/preload) — long enough for
    # browsers to stick to HTTPS, short enough to back out of safely.
    SECURE_HSTS_SECONDS = 3600


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pool",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# WhiteNoise serves static files in production (gunicorn, no nginx). In DEBUG the
# staticfiles app serves them, so we skip WhiteNoise to avoid the missing-dir warning.
if not DEBUG:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

ROOT_URLCONF = "worldcup26.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "worldcup26.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# SQLite in dev and production. On Railway, point SQLITE_PATH at the mounted
# volume (e.g. /data/db.sqlite3) so the database survives deploys.
# WAL: reads don't block while the scheduler writes results; timeout waits on
# locks instead of raising "database is locked".
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("SQLITE_PATH", BASE_DIR / "db.sqlite3"),
        "OPTIONS": {
            "timeout": 20,
            "init_command": "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
        },
    }
}

# Local-memory cache backs the rate limiter (pool/services/throttle.py).
# Per-process: exact with gunicorn's single worker; N workers multiply the
# effective limit by N, which is still bounded. Resets on restart.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"

STATIC_ROOT = BASE_DIR / "staticfiles"


# Sessions — persistent long-lived cookie so users stay logged in between
# visits without re-authenticating (spec section 10).

SESSION_COOKIE_AGE = 60 * 60 * 24 * 365  # 1 year
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True  # slides expiry forward on each visit


# api.fifa.com v3 — the pool's data source. Undocumented public endpoint, no
# API key. Defaults target the FIFA World Cup 2026 (competition 17, season
# 285023); both come from the match-centre URL path. Called only by the
# seed_world_cup / check_results commands, never in a request path.

FIFA_API_BASE_URL = os.environ.get("FIFA_API_BASE_URL", "https://api.fifa.com/api/v3")
FIFA_COMPETITION_ID = os.environ.get("FIFA_COMPETITION_ID", "17")
FIFA_SEASON_ID = os.environ.get("FIFA_SEASON_ID", "285023")
# MatchStatus integer codes that mean "finished" (reverse-engineered: 0).
# Comma-separated env override once live codes are confirmed during the cup.
FIFA_FINISHED_STATUSES = tuple(
    int(code) for code in os.environ.get("FIFA_FINISHED_STATUSES", "0").split(",") if code.strip()
)


# Logging — pool app logs to stderr so Railway captures API failures
# (spec section 9, resilience). Never log the API key.

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "pool": {"handlers": ["console"], "level": "INFO"},
    },
}
