# Generated by Django 6.0.5 on 2026-06-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_rename_round_to_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingentry',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rankingentry',
            name='phase_exact_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rankingentry',
            name='phase_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rankingentry',
            name='phase_winner_hit_count',
            field=models.IntegerField(default=0),
        ),
    ]
